# Generated by Django 2.2 on 2021-07-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_add_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='habit',
            field=models.IntegerField(choices=[(1, '做题模式'), (2, '背题模式')], default=1, verbose_name='看题习惯'),
        ),
    ]
