# Generated by Django 2.2 on 2021-07-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_testmessage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testmessage',
            unique_together=set(),
        ),
    ]
