# Generated by Django 2.2 on 2021-06-29 17:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0008_auto_20210626_1712'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usertest',
            unique_together={('user', 'test')},
        ),
    ]
