# Generated by Django 2.2 on 2021-07-02 19:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0009_auto_20210702_1956'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0003_userfavourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('is_active', models.IntegerField(default=1, verbose_name='是否启用')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.Test', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '提交试题记录',
                'verbose_name_plural': '提交试题记录',
                'unique_together': {('user', 'test')},
            },
        ),
        migrations.CreateModel(
            name='TestVerify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('is_verify', models.IntegerField(default=0, verbose_name='是否审核')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.Test', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='审核员')),
            ],
            options={
                'verbose_name': '试题审核记录',
                'verbose_name_plural': '试题审核记录',
                'unique_together': {('user', 'test')},
            },
        ),
    ]
