# Generated by Django 2.2 on 2021-07-04 16:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0011_auto_20210704_1643'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0004_testverify_usersubmit'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestObjection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('content', models.TextField(verbose_name='异议内容')),
                ('is_active', models.IntegerField(default=0, verbose_name='是否有效')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.Test', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '试题异议',
                'verbose_name_plural': '试题异议',
                'unique_together': {('user', 'test')},
            },
        ),
    ]
