# Generated by Django 2.2 on 2021-06-25 15:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('subject', models.CharField(choices=[('1', '计算机网络'), ('2', '计算机操作系统'), ('3', 'python基础'), ('4', 'java基础')], max_length=20, verbose_name='知识方向')),
                ('point', models.CharField(max_length=20, verbose_name='知识点')),
            ],
            options={
                'verbose_name': '试题类型',
                'verbose_name_plural': '试题类型',
                'unique_together': {('subject', 'point')},
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('difficulty', models.CharField(choices=[('1', '简单'), ('2', '中等'), ('3', '困难')], max_length=1, verbose_name='试题难度')),
                ('style', models.CharField(choices=[('1', '单选'), ('2', '多选'), ('3', '判断'), ('4', '填空')], max_length=1, verbose_name='试题难度')),
                ('desc', models.CharField(max_length=512, verbose_name='试题描述')),
                ('answer', models.CharField(max_length=200, verbose_name='试题答案')),
                ('explain', models.TextField(verbose_name='试题解答')),
                ('all_nums', models.IntegerField(default=1, verbose_name='被做次数')),
                ('correct_nums', models.IntegerField(default=1, verbose_name='做对次数')),
                ('collection_nums', models.IntegerField(default=1, verbose_name='收藏次数')),
                ('select_nums', models.IntegerField(default=0, verbose_name='选项个数')),
                ('select_a', models.CharField(max_length=50, verbose_name='选项a')),
                ('select_b', models.CharField(max_length=50, verbose_name='选项b')),
                ('select_c', models.CharField(max_length=50, verbose_name='选项c')),
                ('select_d', models.CharField(max_length=50, verbose_name='选项d')),
                ('select_e', models.CharField(max_length=50, verbose_name='选项e')),
                ('select_f', models.CharField(max_length=50, verbose_name='选项f')),
                ('select_g', models.CharField(max_length=50, verbose_name='选项g')),
                ('select_h', models.CharField(max_length=50, verbose_name='选项h')),
                ('select_i', models.CharField(max_length=50, verbose_name='选项i')),
                ('subject_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.TestSubject', verbose_name='试题类型')),
            ],
            options={
                'verbose_name': '试题描述',
                'verbose_name_plural': '试题描述',
            },
        ),
    ]
