# Generated by Django 2.2 on 2021-06-25 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_remove_test_select_i'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('1', '待审核'), ('2', '退回'), ('3', '启用'), ('4', '异议待审核'), ('5', '异议退回')], default='1', max_length=1, verbose_name='试题状态'),
        ),
        migrations.AddField(
            model_name='test',
            name='threshold',
            field=models.IntegerField(default=5, verbose_name='异议阈值'),
        ),
        migrations.AlterField(
            model_name='test',
            name='style',
            field=models.CharField(choices=[('1', '单选'), ('2', '多选'), ('3', '判断'), ('4', '填空')], max_length=1, verbose_name='试题类型'),
        ),
        migrations.AlterField(
            model_name='test',
            name='subject_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.TestSubject', verbose_name='试题知识点'),
        ),
    ]
