# Generated by Django 2.2 on 2021-06-26 17:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0007_auto_20210625_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('point', models.CharField(max_length=20, verbose_name='知识点')),
            ],
            options={
                'verbose_name': '知识点',
                'verbose_name_plural': '知识点',
            },
        ),
        migrations.AlterModelOptions(
            name='testsubject',
            options={'verbose_name': '知识方向', 'verbose_name_plural': '知识方向'},
        ),
        migrations.AlterField(
            model_name='test',
            name='subject_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.TestPoint', verbose_name='试题知识点'),
        ),
        migrations.AlterField(
            model_name='testsubject',
            name='subject',
            field=models.CharField(max_length=20, verbose_name='知识方向'),
        ),
        migrations.AlterUniqueTogether(
            name='testsubject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='testpoint',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test.TestSubject', verbose_name='知识方向'),
        ),
        migrations.RemoveField(
            model_name='testsubject',
            name='point',
        ),
        migrations.AlterUniqueTogether(
            name='testpoint',
            unique_together={('subject', 'point')},
        ),
    ]
