# Generated by Django 2.2 on 2021-07-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0008_auto_20210626_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('1', '待审核'), ('2', '异议退回'), ('3', '启用'), ('4', '废弃')], default='1', max_length=1, verbose_name='试题状态'),
        ),
    ]
