# Generated by Django 2.2 on 2021-08-13 19:45

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0011_auto_20210704_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='explain',
            field=DjangoUeditor.models.UEditorField(default='暂无', verbose_name='试题解答'),
        ),
    ]
