# Generated by Django 2.2 on 2021-08-13 20:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0012_auto_20210813_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='explain',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='暂无', verbose_name='试题解答'),
        ),
    ]
