# Generated by Django 2.2 on 2021-08-20 23:36

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0013_auto_20210813_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='试题描述'),
        ),
    ]
