# Generated by Django 2.2 on 2021-06-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_auto_20210625_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': '试题集', 'verbose_name_plural': '试题集'},
        ),
        migrations.AlterField(
            model_name='test',
            name='collection_nums',
            field=models.IntegerField(default=0, verbose_name='收藏次数'),
        ),
        migrations.AlterField(
            model_name='test',
            name='explain',
            field=models.TextField(default='暂无', verbose_name='试题解答'),
        ),
        migrations.AlterField(
            model_name='test',
            name='select_a',
            field=models.CharField(default=None, max_length=50, verbose_name='选项a'),
        ),
        migrations.AlterField(
            model_name='test',
            name='select_b',
            field=models.CharField(default=None, max_length=50, verbose_name='选项b'),
        ),
        migrations.AlterField(
            model_name='test',
            name='select_c',
            field=models.CharField(default=None, max_length=50, verbose_name='选项c'),
        ),
        migrations.AlterField(
            model_name='test',
            name='select_d',
            field=models.CharField(default=None, max_length=50, verbose_name='选项d'),
        ),
        migrations.AlterField(
            model_name='test',
            name='select_e',
            field=models.CharField(default=None, max_length=50, verbose_name='选项e'),
        ),
        migrations.AlterField(
            model_name='test',
            name='select_f',
            field=models.CharField(default=None, max_length=50, verbose_name='选项f'),
        ),
        migrations.AlterField(
            model_name='test',
            name='select_g',
            field=models.CharField(default=None, max_length=50, verbose_name='选项g'),
        ),
        migrations.AlterField(
            model_name='test',
            name='select_h',
            field=models.CharField(default=None, max_length=50, verbose_name='选项h'),
        ),
    ]
