# Generated by Django 2.2 on 2021-06-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0006_auto_20210625_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='desc',
            field=models.TextField(verbose_name='试题描述'),
        ),
    ]
