# Generated by Django 2.2 on 2021-07-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0010_auto_20210703_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='objection_nums',
            field=models.IntegerField(default=0, verbose_name='异议次数'),
        ),
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('1', '待审核'), ('2', '异议退回'), ('3', '启用'), ('4', '仅自己可见'), ('5', '废弃')], default='1', max_length=1, verbose_name='试题状态'),
        ),
    ]
